image: archlinux
secrets:
- 5c5bf3b5-a730-49d9-b46a-cb6baa48092d
packages:
- emacs-nox
- jq
sources:
- https://git.sr.ht/~fosskers/transducers.el
tasks:
- test: |
    cd transducers.el
    emacs --batch -l transducers.el -l transducers-test.el  -f ert-run-tests-batch-and-exit
- readme: |
    cd transducers.el
    emacs README.org --batch --eval "(setq org-html-head-include-default-style nil)" -f org-html-export-to-html --kill
    sed -i '/<title>/d; /<\/title>/d' README.html
- upload: |
    cd transducers.el
    set +x  # Avoid echoing the token
    jq -sR '{
        "query": "mutation UpdateRepo($id: Int!, $readme: String!) {
          updateRepository(id: $id, input: { readme: $readme }) { id }
        }", "variables": {
          "id": 364843,
          "readme": .
        } }' < README.html \
      | curl --oauth2-bearer $(cat ~/.readme-token) \
        -H "Content-Type: application/json" \
        -d@- https://git.sr.ht/query
    echo "README Uploaded."
